logging:
  level:
    br.com.rodrigoaralmeida.examples: debug
spring:
  application:
    name: 'app client'
  config:
    import:
    - optional:configserver:http://localhost:8888
  cloud:
    config:
      profile: pd
    